databases:
  - name: attendease-db
    databaseName: attendease
    user: attendease
    plan: free
    region: frankfurt

services:
  - type: web
    name: attendease-app
    env: docker
    plan: free
    region: frankfurt
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: attendease-db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
